
    <div class="main-login">
        <div class="left-login">
            <h1>Faça Login<br> E acesse nossos planos!</h1>
            <img src="assets/img/animate-login.svg" alt="Animação" class="imgLogin"/>
        </div>
        <div class="right-login">
            <div class="card-login">
                <h1>LOGIN</h1>
                <form method="POST" id="formLogin">
                    <div class="textfield">
                        <label for="emailIn">E-Mail</label>
                        <input type="text" id="emailIn" name="emailIn" placeholder="E-Mail"/>
                    </div>
                    <div class="textfield">
                        <label for="senhaIn">Senha</label>
                        <input type="password" id="senhaIn" name="senha" placeholder="Senha"/>
                    </div>
                    <div id="mConect">
                        <input type="checkbox" id="cbConectIn"><label for="cbConectIn">Manter-me conectado</label>
                    </div>
                    <button type="submit" class="btn-login">Login</button>
                </form>
                <p class="redCad" onclick="redirect('/cadastro')">Cadastre-se</p>
                <p class="redRes" onclick="redirect('/restaurar')">Esqueci minha senha</p>
            </div>
        </div>
    </div>
