<div class="fsh restaurarSenha">
    <div class="cardResSenha">
        <h3 class="titleResSenha">Recuperar senha</h3>
        <form id="formResSenha" action="/enviarRestauracao" method="POST">
            <label class="lblResSenha">Digite seu email: </label><br>
            <input class="inputResSenha" name="emailRes" id="inputResSenha" type="text"/><br>
            <button class="envResSenha" type="button">Enviar</button>
        </form>
    </div>
</div>