<div class="fsh restaurarSenha">
    <div class="cardResSenha">
        <h3 class="titleResSenha">Recuperar senha</h3>
        <form id="formResSenha" action="/enviarRestauracao" method="POST">
            <label for="inputResSenha" class="lblResSenha">Digite o email da conta que deseja recuperar: </label><br>
            <input class="inputResEm" name="emailRes" placeholder="email.email@provedor.com" id="inputResEm" type="text"/><br>
            <button class="envResSenha" id="envResSenhaEm" type="button">Enviar</button>
        </form>
    </div>
</div>