<div class="fsh alterarDados">
    <div class="atDados sw">
        <div class="cardAtDados">
            <h2 class="titleAtDados">Alterar Dados</h2>
            <form method="POST" action="/envAtDados" id="formAtDados">
                <label class="tipAt" for="nomeAt">Nome: <a class="statusNome"></a></label><br>
                <input class="inputAtDados" type="text" name="nomeAt" id="nomeAt" value="<?php echo $this->view->usuario['nome']; ?>"/><br>
                <label class="tipAt" for="telAt">Telefone: </label><br>
                <input class="inputAtDados" type="text" name="telAt" id="telAt" value="<?php echo $this->view->usuario['telefone']; ?>"/><br>
                <label class="tipAt" for="emailAt">Email: </label><br>
                <input class="inputAtDados" type="email" name="emailAt" id="emailAt" value="<?php echo $this->view->usuario['email']; ?>"/><br>
                <label class="tipAt" for="senhaAtAnt">Senha Antiga: </label><br>
                <input class="inputAtDados" type="password" name="senhaAtAnt" id="senhaAtAnt"/><br>
                <label class="tipAt" for="senhaAt">Nova Senha: </label><br>
                <input class="inputAtDados" type="password" name="senhaAt" id="senhaAt"/><br>
                <button type="button" class="btnAtDados">Atualizar</button>
            </form>
        </div>
    </div>
</div>