<div class="f meuProjeto">
    <div class="projeto sw">
        <div class="infosProjeto">
        <?php
            if($this->view->projeto != false) {
                ?>
                    <h3 class="titleProjeto"><?= $this->view->projeto['nomePlano'] ?></h3>
                    <p class="infosProjetoText"><?= $this->view->projeto['descricaoPlano'] ?></p>
                    <p class="infosProjetoText valorProjeto">R$<?= floatval($this->view->projeto['valorInicial']) +  floatval($this->view->projeto['valorAdicional']) ?></p>
                <?php
            }
            else {
                ?>
                    <h3 class="titleProjeto">Não há projeto em sua conta.</h3>
                    <p class="infosProjetoText">Busque o seu <a href="/planos">melhor plano</a> para abrir um e começar o desenvolvimento!</p>
                <?php
            }
        ?>
            <div class="atProj">
                <h3 class="titleMProjeto">Andamento de projeto</h3>
                <p class="infosMProjeto">Situação: <?php echo $this->view->dadosProj['situacao']; ?></p>    
                <p class="infosMProjeto">Previsão: <?php echo $this->view->dadosProj['previsao']; ?></p>  
                <p class="infosMProjeto">Atualização: <?php echo $this->view->dadosProj['atualizacao']; ?></p>  
                <p class="infosMProjeto">Data de atualização: <?php echo str_replace('-', '/', date('d-m-Y', strtotime($this->view->dadosProj['dataAt']))); ?></p>    
                <p class="infosMProjeto">Imagens: <?php echo $this->view->dadosProj['imagens']; ?></p>    
            </div>
        </div>
        <div class="direitosPlano">
            <div class="infoDireitosPlano">
                <h3 class="titleDireitos">Com o plano profissional você tem direito a:</h3>
                <p></p>
            </div>
        </div>
    </div>  
</div>