<div class="f minhaConta">
    <div class="perfil sw">
        <div class="infosConta">
            <h1 class="titleMConta">Minha Conta</h1>
            <img class="imgConta" src="assets/img/default.png"/>
            <p class="nomeConta infoConta"><b>Nome:</b> <?php echo $this->view->usuario['nome']; ?></p>
            <p class="telConta infoConta"><b>Telefone:</b> <?php echo $this->view->usuario['telefone']; ?></p>
            <p class="emailConta infoConta"><b>Email:</b> <?php echo $this->view->usuario['email']; ?></p>
            <p class="infoConta"><b>Logradouro:</b> <?php echo $this->view->usuario['logradouro']; ?></p>
        </div>
        <button class="alterarDados" onclick="redirect('/alterarDados')">Alterar dados</button>
    </div>
</div>