<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mini-framework</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="assets/css/login.css?<?php echo time(); ?>"/>
    <link rel="stylesheet" href="assets/css/cadastro.css?<?php echo time(); ?>"/>
    <link rel="stylesheet" href="assets/css/main.css?<?php echo time(); ?>"/>
    <link rel="stylesheet" href="assets/css/restaurarSenha.css?<?php echo time(); ?>"/>
    <link rel="stylesheet" href="assets/css/alterarDados.css?<?php echo time(); ?>"/>
    <script type="text/javascript" src="assets/js/redirects.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="assets/js/ajax.js"></script>
    <script type="text/javascript" src="assets/js/main.js"></script>
    <script crossorigin="anonimous" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
</head>
<body>
    <?php $this->content() ?>
</body>
</html>